// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// arcs.cpp
cpp11::list find_arcs_cpp(cpp11::integers i0, cpp11::integers i1, cpp11::integers ids);
extern "C" SEXP _wkpool_find_arcs_cpp(SEXP i0, SEXP i1, SEXP ids) {
  BEGIN_CPP11
    return cpp11::as_sexp(find_arcs_cpp(cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i0), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(i1), cpp11::as_cpp<cpp11::decay_t<cpp11::integers>>(ids)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_wkpool_find_arcs_cpp", (DL_FUNC) &_wkpool_find_arcs_cpp, 3},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_wkpool(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
